/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InstitucionVistas;

import Institucion.modelo.Alumno;
import Institucion.modelo.Materia;
import java.util.ArrayList;

/**
 *
 * @author Macarena Infante
 */
public class Principal extends javax.swing.JFrame {
    
    public static ArrayList<Alumno> alumnos = new ArrayList<> ();
    public static ArrayList<Materia> materias = new ArrayList<>();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        menuMaterias = new javax.swing.JMenu();
        menuItemFormularioMaterias = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuItemFormularioAlumnos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuItemInscripciones = new javax.swing.JMenuItem();
        menuNotas = new javax.swing.JMenu();
        menuItemManejoNotas = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        menuItemAlumnosxMateria = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        menuMaterias.setText("Materias");

        menuItemFormularioMaterias.setText("Formulario de Materias");
        menuItemFormularioMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormularioMateriasActionPerformed(evt);
            }
        });
        menuMaterias.add(menuItemFormularioMaterias);

        jMenuBar3.add(menuMaterias);

        jMenu7.setText("Alumnos");

        menuItemFormularioAlumnos.setText("Formulario de Alumnos");
        menuItemFormularioAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormularioAlumnosActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemFormularioAlumnos);

        jMenuBar3.add(jMenu7);

        jMenu8.setText("Inscripciones");

        menuItemInscripciones.setText("Manejo de Inscripciones");
        menuItemInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInscripcionesActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemInscripciones);

        jMenuBar3.add(jMenu8);

        menuNotas.setText("Notas");

        menuItemManejoNotas.setText("Manejo de Notas");
        menuItemManejoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemManejoNotasActionPerformed(evt);
            }
        });
        menuNotas.add(menuItemManejoNotas);

        jMenuBar3.add(menuNotas);

        jMenu9.setText("Consultas");

        menuItemAlumnosxMateria.setText("Alumnos x Materias");
        menuItemAlumnosxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlumnosxMateriaActionPerformed(evt);
            }
        });
        jMenu9.add(menuItemAlumnosxMateria);

        jMenuBar3.add(jMenu9);

        menuSalir.setText("Salir");

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(menuItemSalir);

        jMenuBar3.add(menuSalir);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFormularioMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormularioMateriasActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaMaterias vistaMaterias = new VistaMaterias(materias);
        vistaMaterias.setVisible(true);
        escritorio.add(vistaMaterias);
        escritorio.moveToFront(vistaMaterias);
        escritorio.repaint();
        
    }//GEN-LAST:event_menuItemFormularioMateriasActionPerformed

    private void menuItemFormularioAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormularioAlumnosActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaAlumnos vistaAlumnos = new VistaAlumnos(alumnos);
        vistaAlumnos.setVisible(true);
        escritorio.add(vistaAlumnos);
        escritorio.moveToFront(vistaAlumnos);
        escritorio.repaint();
        
    }//GEN-LAST:event_menuItemFormularioAlumnosActionPerformed

    private void menuItemInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInscripcionesActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaInscripciones vistaInscripciones = new VistaInscripciones();
        vistaInscripciones.setVisible(true);
        escritorio.add(vistaInscripciones);
        escritorio.moveToFront(vistaInscripciones);
        escritorio.repaint();
        
    }//GEN-LAST:event_menuItemInscripcionesActionPerformed

    private void menuItemManejoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemManejoNotasActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaNotas vistaNotas = new VistaNotas();
        vistaNotas.setVisible(true);
        escritorio.add(vistaNotas);
        escritorio.moveToFront(vistaNotas);
        escritorio.repaint();
        
    }//GEN-LAST:event_menuItemManejoNotasActionPerformed

    private void menuItemAlumnosxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlumnosxMateriaActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();        
        VistaConsultas vistaConsultas = new VistaConsultas();
        vistaConsultas.setVisible(true);
        escritorio.add(vistaConsultas);
        escritorio.moveToFront(vistaConsultas);
        escritorio.repaint();  
        
    }//GEN-LAST:event_menuItemAlumnosxMateriaActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_menuItemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuItemAlumnosxMateria;
    private javax.swing.JMenuItem menuItemFormularioAlumnos;
    private javax.swing.JMenuItem menuItemFormularioMaterias;
    private javax.swing.JMenuItem menuItemInscripciones;
    private javax.swing.JMenuItem menuItemManejoNotas;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuMaterias;
    private javax.swing.JMenu menuNotas;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
